# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b1728ae1dc79899e442032f8420240ff52cb5802d1402a4b509a6b62d33ff8ec6ef8e8815b8e56a9c825660b837eeed9d65c72508b19f2c98ab9221ef67454d

test:
  secret_key_base: 416398737bc82e77c56c15b8a5a9ffb1a485dfdb04638bfb70f14a18323dbaba3c2176d0c1819dcf7777c4fbc9c0e76f0b9b35e56e23de5f53d67e392d049d0c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
