class Step < ApplicationRecord

  belongs_to :recipe


  def self.show_appliances
    appliances = [
      "air fryer",
      "bachelor griller",
      "barbecue grill",
      "beehive oven",
      "brasero",
      "brazier",
      "bread machine",
      "burjiko",
      "butane torch",
      "cheesemelter",
      "chocolatera",
      "chorkor oven",
      "clome oven",
      "comal",
      "combi steamer",
      "communal oven",
      "convection microwave",
      "convection oven",
      "corn roaster",
      "crepe maker",
      "deep fryer",
      "earth oven",
      "electric cooker",
      "energy regulator",
      "espresso machine",
      "field kitchen",
      "fire pot",
      "flattop grill",
      "food steamer",
      "fufu machine",
      "halogen oven",
      "haybox",
      "horno",
      "hot box",
      "hot plate",
      "instant pot",
      "kamado",
      "kettle",
      "kitchener range",
      "kujiejun",
      "kyoto box",
      "masonry oven",
      "mess kit",
      "microwave oven",
      "multicooker",
      "oven",
      "pancake machine",
      "panini sandwich grill",
      "popcorn maker",
      "pressure cooker",
      "pressure fryer",
      "reflector oven",
      "remoska",
      "rice cooker",
      "rice polisher",
      "roasting jack",
      "rocket mass heater",
      "rotimatic",
      "rotisserie",
      "russian oven",
      "sabbath mode",
      "salamander broiler",
      "samovar",
      "sandwich toaster",
      "self-cleaning oven",
      "set-n-forget cooker",
      "shichirin",
      "slow cooker",
      "solar cooker",
      "sous-vide cooker",
      "soy milk maker",
      "stove",
      "susceptor",
      "tabun oven",
      "tandoor",
      "tangia",
      "thermal immersion circulator",
      "toaster and toaster ovens",
      "turkey fryer",
      "vacuum fryer",
      "waffle iron",
      "wet grinder",
      "wood-fired oven",
      "coffee percolator",
      "coffeemaker",
      "electric water boiler",
      "instant hot water dispenser",
      "pan",
      "pot",
      "wok",
      "oven",
      "grill",
      "stick blender",
      "food processor"
    ]
    matches = []
    appliances.each { |appliance|
      steps = Step.where("content LIKE (?)", "%#{appliance}%")
      if steps.any?
        steps.each { |step|
          matches << "step id: #{step.id} contains #{appliance}"
        }
      end
    }
    return matches
  end

end
